execute_process(COMMAND "${RABBITBIN}" --version
                RESULT_VARIABLE RC OUTPUT_VARIABLE VERSION_OUTPUT
                ERROR_VARIABLE VERSION_ERROR OUTPUT_STRIP_TRAILING_WHITESPACE)
set(EXPECTED "RabbitBin ${EXPECTED_VERSION} (commit ${EXPECTED_REVISION})")
if(NOT RC EQUAL 0 OR NOT VERSION_OUTPUT STREQUAL EXPECTED)
  message(FATAL_ERROR
    "Version check failed (${RC}): expected '${EXPECTED}', got '${VERSION_OUTPUT}'\n${VERSION_ERROR}")
endif()
